services:
  db:
    image: postgres:latest
    container_name: videoflix_database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/pgdata # FIX FOR PG 18 ERROR
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_1:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: videoflix_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data_1:/data

volumes:
  postgres_data_1:
  redis_data_1:

