# Generated by Django 5.2.4 on 2026-04-01 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_thumbnail_video_video_file_alter_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='genre',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='release_date',
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 4, 1, 8, 57, 33, 521400, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
